Repository AY2122S2-CS2103-W16-2/tp, pull requests merged in 2022-03, with the labels that each got.

#123 Bump version for 1.3 trial release
  src/main/java/seedu/address/MainApp.java
Labels: urgent

#124 Update DG for Add, Delete, and Find use cases
  docs/DeveloperGuide.md
Labels: type.Documentation

#125 Update Developer Guide to include Implementation of Dynamic Text Field
  docs/DeveloperGuide.md
  docs/diagrams/DynamicInputFindDiagram.puml
  docs/images/DynamicInputFindDiagram.png
Labels: type.Documentation

#121 Add implementation for Target class into DG
  docs/DeveloperGuide.md
  docs/diagrams/TargetClass.puml
  docs/images/TargetClass.png
  src/main/java/seedu/address/logic/commands/delete/Target.java
Labels: type.Documentation, urgent
